version: '3.1'
services:
 db:
   image: postgres:latest
   container_name: db_assistencia
   environment:
     - POSTGRES_DB=assistencia_db
     - POSTGRES_PASSWORD=passardhon
     - POSTGRES_USER=userardhon
   ports:
     - "5432:5432"
   #volumes:
     #- local_pgdata:/var/lib/postgresql/data
 pgadmin:
   image: dpage/pgadmin4
   container_name: pg_assistencia
   ports:
     - "80:80"
   environment:
     PGADMIN_DEFAULT_EMAIL: ardhon@ardhon.com
     PGADMIN_DEFAULT_PASSWORD: passardhon
   #volumes:
     #- pgadmin-data:/var/lib/pgadmin
#volumes:
 #local_pgdata:
 #pgadmin-data: